[package]
name = "boom"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
tui = "0.17.0"
crossterm = "0.23.0"
serde_json="*"
rand="*"