[package]
name = "boom"
version = "0.1.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3.3"
tui = "0.17.0"
crossterm = "0.23.0"
serde_json = "1.0.79"
rand = "0.8.5"
chrono = { version = "0.4", features = ["serde"] }
figlet-rs = "0.1.3"
